### ISSUE TITLE
There is no dataset for base stations

### ISSUE THREAD

**Issue by ZhuiMeng3DNA** [BuptMecMigration/Edge-Computing-Dataset#1]
There is no dataset for base stations

**Comment by Zplusless** [comment]
please clone this project, the data csv files are in "Data" folder

**Comment by Zplusless** [comment]
> There is no dataset for base stations

please clone this project, the data csv files are in "Data" folder

**Comment by Zplusless** [comment]
> There is no dataset for base stations

base stations are identified by Location Area Code(second column) and Cell Identity(third column)

**Comment by ZhuiMeng3DNA** [comment]
> 

Thank you for your answer
